use crate::model::FPSCountry;
use serde::Deserialize;
use strum::AsStaticStr;

#[derive(Debug, AsStaticStr, Deserialize, PartialEq, Eq, Hash, Clone)]
pub enum Country {
    AL,
    AD,
    AT,
    AZ,
    BY,
    BE,
    BA,
    BG,
    HR,
    CY,
    CZ,
    DK,
    EE,
    FO,
    FI,
    FR,
    DE,
    GI,
    GR,
    GL,
    GG,
    HU,
    IS,
    IE,
    IT,
    JE,
    KV,
    LV,
    LI,
    LT,
    LU,
    MT,
    MD,
    MC,
    ME,
    NL,
    MK,
    NO,
    PL,
    PT,
    RO,
    RU,
    SM,
    RS,
    SK,
    SI,
    ES,
    IC,
    SE,
    CH,
    TR,
    UA,
    GB,
    VA,
    CA,
    PR,
    US,
}

impl Country {
    pub fn fps_base_url(&self) -> &'static str {
        {
            match self {
                Country::AL => "https://www.blackandwhite-ff.com/en-al",
                Country::AD => "https://www.blackandwhite-ff.com/en-ad",
                Country::AT => "https://www.blackandwhite-ff.com/en-at",
                Country::AZ => "https://www.blackandwhite-ff.com/en-az",
                Country::BY => "https://www.blackandwhite-ff.com/en-by",
                Country::BE => "https://www.blackandwhite-ff.com/en-be",
                Country::BA => "https://www.blackandwhite-ff.com/en-ba",
                Country::BG => "https://www.blackandwhite-ff.com/en-bg",
                Country::HR => "https://www.blackandwhite-ff.com/en-hr",
                Country::CY => "https://www.blackandwhite-ff.com/en-cy",
                Country::CZ => "https://www.blackandwhite-ff.com/en-cz",
                Country::DK => "https://www.blackandwhite-ff.com/en-dk",
                Country::EE => "https://www.blackandwhite-ff.com/en-ee",
                Country::FO => "https://www.blackandwhite-ff.com/en-fo",
                Country::FI => "https://www.blackandwhite-ff.com/en-fi",
                Country::FR => "https://www.blackandwhite-ff.com/en-fr",
                Country::DE => "https://www.blackandwhite-ff.com/en-de",
                Country::GI => "https://www.blackandwhite-ff.com/en-gi",
                Country::GR => "https://www.blackandwhite-ff.com/en-gr",
                Country::GL => "https://www.blackandwhite-ff.com/en-gl",
                Country::GG => "https://www.blackandwhite-ff.com/en-gg",
                Country::HU => "https://www.blackandwhite-ff.com/en-hu",
                Country::IS => "https://www.blackandwhite-ff.com/en-is",
                Country::IE => "https://www.blackandwhite-ff.com/en-ie",
                Country::IT => "https://www.blackandwhite-ff.com/it-it",
                Country::JE => "https://www.blackandwhite-ff.com/en-je",
                Country::KV => "https://www.blackandwhite-ff.com/en-kv",
                Country::LV => "https://www.blackandwhite-ff.com/en-lv",
                Country::LI => "https://www.blackandwhite-ff.com/en-li",
                Country::LT => "https://www.blackandwhite-ff.com/en-lt",
                Country::LU => "https://www.blackandwhite-ff.com/en-lu",
                Country::MT => "https://www.blackandwhite-ff.com/en-mt",
                Country::MD => "https://www.blackandwhite-ff.com/en-md",
                Country::MC => "https://www.blackandwhite-ff.com/en-mc",
                Country::ME => "https://www.blackandwhite-ff.com/en-me",
                Country::NL => "https://www.blackandwhite-ff.com/en-nl",
                Country::MK => "https://www.blackandwhite-ff.com/en-mk",
                Country::NO => "https://www.blackandwhite-ff.com/en-no",
                Country::PL => "https://www.blackandwhite-ff.com/en-pl",
                Country::PT => "https://www.blackandwhite-ff.com/en-pt",
                Country::RO => "https://www.blackandwhite-ff.com/en-ro",
                Country::RU => "https://www.blackandwhite-ff.com/en-ru",
                Country::SM => "https://www.blackandwhite-ff.com/en-sm",
                Country::RS => "https://www.blackandwhite-ff.com/en-rs",
                Country::SK => "https://www.blackandwhite-ff.com/en-sk",
                Country::SI => "https://www.blackandwhite-ff.com/en-si",
                Country::ES => "https://www.blackandwhite-ff.com/en-es",
                Country::IC => "https://www.blackandwhite-ff.com/en-ic",
                Country::SE => "https://www.blackandwhite-ff.com/en-se",
                Country::CH => "https://www.blackandwhite-ff.com/en-ch",
                Country::TR => "https://www.blackandwhite-ff.com/en-tr",
                Country::UA => "https://www.blackandwhite-ff.com/en-ua",
                Country::GB => "https://www.blackandwhite-ff.com/en-gb",
                Country::VA => "https://www.blackandwhite-ff.com/en-va",
                Country::CA => "https://www.blackandwhite-ff.com/en-ca",
                Country::PR => "https://www.blackandwhite-ff.com/en-pr",
                Country::US => "https://www.blackandwhite-ff.com/en-us",
            }
        }
    }

    pub fn fps_country(&self) -> &'static FPSCountry {
        {
            match self {
                Country::AL => &FPSCountry {
                    id: 2,
                    name: "Albania",
                },
                Country::AD => &FPSCountry {
                    id: 307,
                    name: "Andorra",
                },
                Country::AT => &FPSCountry {
                    id: 13,
                    name: "Austria",
                },
                Country::AZ => &FPSCountry {
                    id: 14,
                    name: "Azerbaijan",
                },
                Country::BY => &FPSCountry {
                    id: 19,
                    name: "Belarus",
                },
                Country::BE => &FPSCountry {
                    id: 20,
                    name: "Belgium",
                },
                Country::BA => &FPSCountry {
                    id: 304,
                    name: "Bosnia and Herzegovina",
                },
                Country::BG => &FPSCountry {
                    id: 31,
                    name: "Bulgaria",
                },
                Country::HR => &FPSCountry {
                    id: 51,
                    name: "Croatia",
                },
                Country::CY => &FPSCountry {
                    id: 52,
                    name: "Cyprus",
                },
                Country::CZ => &FPSCountry {
                    id: 53,
                    name: "Czech Republic",
                },
                Country::DK => &FPSCountry {
                    id: 54,
                    name: "Denmark",
                },
                Country::EE => &FPSCountry {
                    id: 63,
                    name: "Estonia",
                },
                Country::FO => &FPSCountry {
                    id: 65,
                    name: "Faeroe Islands",
                },
                Country::FI => &FPSCountry {
                    id: 69,
                    name: "Finland",
                },
                Country::FR => &FPSCountry {
                    id: 70,
                    name: "France",
                },
                Country::DE => &FPSCountry {
                    id: 77,
                    name: "Germany",
                },
                Country::GI => &FPSCountry {
                    id: 79,
                    name: "Gibraltar",
                },
                Country::GR => &FPSCountry {
                    id: 80,
                    name: "Greece",
                },
                Country::GL => &FPSCountry {
                    id: 81,
                    name: "Greenland",
                },
                Country::GG => &FPSCountry {
                    id: 86,
                    name: "Guernsey, C.I.",
                },
                Country::HU => &FPSCountry {
                    id: 94,
                    name: "Hungary",
                },
                Country::IS => &FPSCountry {
                    id: 95,
                    name: "Iceland",
                },
                Country::IE => &FPSCountry {
                    id: 98,
                    name: "Ireland",
                },
                Country::IT => &FPSCountry {
                    id: 101,
                    name: "Italy",
                },
                Country::JE => &FPSCountry {
                    id: 104,
                    name: "Jersey, C.I.",
                },
                Country::KV => &FPSCountry {
                    id: 311,
                    name: "Kosovo",
                },
                Country::LV => &FPSCountry {
                    id: 113,
                    name: "Latvia",
                },
                Country::LI => &FPSCountry {
                    id: 117,
                    name: "Liechtenstein",
                },
                Country::LT => &FPSCountry {
                    id: 118,
                    name: "Lithuania",
                },
                Country::LU => &FPSCountry {
                    id: 119,
                    name: "Luxembourg",
                },
                Country::MT => &FPSCountry {
                    id: 126,
                    name: "Malta",
                },
                Country::MD => &FPSCountry {
                    id: 133,
                    name: "Moldova, Republic of",
                },
                Country::MC => &FPSCountry {
                    id: 134,
                    name: "Monaco",
                },
                Country::ME => &FPSCountry {
                    id: 302,
                    name: "Montenegro",
                },
                Country::NL => &FPSCountry {
                    id: 144,
                    name: "Netherlands",
                },
                Country::MK => &FPSCountry {
                    id: 303,
                    name: "North Macedonia",
                },
                Country::NO => &FPSCountry {
                    id: 153,
                    name: "Norway",
                },
                Country::PL => &FPSCountry {
                    id: 164,
                    name: "Poland",
                },
                Country::PT => &FPSCountry {
                    id: 165,
                    name: "Portugal",
                },
                Country::RO => &FPSCountry {
                    id: 169,
                    name: "Romania",
                },
                Country::RU => &FPSCountry {
                    id: 170,
                    name: "Russian Federation",
                },
                Country::SM => &FPSCountry {
                    id: 175,
                    name: "San Marino",
                },
                Country::RS => &FPSCountry {
                    id: 301,
                    name: "Serbia",
                },
                Country::SK => &FPSCountry {
                    id: 182,
                    name: "Slovakia",
                },
                Country::SI => &FPSCountry {
                    id: 183,
                    name: "Slovenia",
                },
                Country::ES => &FPSCountry {
                    id: 187,
                    name: "Spain",
                },
                Country::IC => &FPSCountry {
                    id: 305,
                    name: "Spain - Canary Islands",
                },
                Country::SE => &FPSCountry {
                    id: 196,
                    name: "Sweden",
                },
                Country::CH => &FPSCountry {
                    id: 197,
                    name: "Switzerland",
                },
                Country::TR => &FPSCountry {
                    id: 207,
                    name: "Turkey",
                },
                Country::UA => &FPSCountry {
                    id: 214,
                    name: "Ukraine",
                },
                Country::GB => &FPSCountry {
                    id: 215,
                    name: "United Kingdom",
                },
                Country::VA => &FPSCountry {
                    id: 220,
                    name: "Vatican City State",
                },
                Country::CA => &FPSCountry {
                    id: 36,
                    name: "Canada",
                },
                Country::PR => &FPSCountry {
                    id: 166,
                    name: "Puerto Rico",
                },
                Country::US => &FPSCountry {
                    id: 216,
                    name: "United States",
                },
            }
        }
    }

    pub fn fps_currency(&self) -> &'static str {
        {
            match self {
                Country::AL => "USD",
                Country::AD => "EUR",
                Country::AT => "EUR",
                Country::AZ => "USD",
                Country::BY => "USD",
                Country::BE => "EUR",
                Country::BA => "EUR",
                Country::BG => "EUR",
                Country::HR => "EUR",
                Country::CY => "EUR",
                Country::CZ => "EUR",
                Country::DK => "DKK",
                Country::EE => "EUR",
                Country::FO => "USD",
                Country::FI => "EUR",
                Country::FR => "EUR",
                Country::DE => "EUR",
                Country::GI => "GBP",
                Country::GR => "EUR",
                Country::GL => "USD",
                Country::GG => "GBP",
                Country::HU => "EUR",
                Country::IS => "USD",
                Country::IE => "EUR",
                Country::IT => "EUR",
                Country::JE => "GBP",
                Country::KV => "USD",
                Country::LV => "EUR",
                Country::LI => "CHF",
                Country::LT => "EUR",
                Country::LU => "EUR",
                Country::MT => "EUR",
                Country::MD => "USD",
                Country::MC => "EUR",
                Country::ME => "EUR",
                Country::NL => "EUR",
                Country::MK => "EUR",
                Country::NO => "USD",
                Country::PL => "PLN",
                Country::PT => "EUR",
                Country::RO => "EUR",
                Country::RU => "RUB",
                Country::SM => "EUR",
                Country::RS => "EUR",
                Country::SK => "EUR",
                Country::SI => "EUR",
                Country::ES => "EUR",
                Country::IC => "EUR",
                Country::SE => "SEK",
                Country::CH => "CHF",
                Country::TR => "EUR",
                Country::UA => "EUR",
                Country::GB => "GBP",
                Country::VA => "EUR",
                Country::CA => "CAD",
                Country::PR => "USD",
                Country::US => "USD",
            }
        }
    }

    pub fn accept_language(&self) -> &'static str {
        {
            match self {
                Country::AL => "sq-AL",
                Country::AD => "en-GB",
                Country::AT => "de-AT",
                Country::AZ => "az-Latn-AZ",
                Country::BY => "be-BY",
                Country::BE => "fr-BE",
                Country::BA => "en-GB",
                Country::BG => "bg-BG",
                Country::HR => "hr-HR",
                Country::CY => "en-GB",
                Country::CZ => "cs-CZ",
                Country::DK => "da-DK",
                Country::EE => "et-EE",
                Country::FO => "en-GB",
                Country::FI => "fi-FI",
                Country::FR => "fr-FR",
                Country::DE => "de-DE",
                Country::GI => "en-GB",
                Country::GR => "el-GR",
                Country::GL => "kl-GL",
                Country::GG => "en-GB",
                Country::HU => "hu-HU",
                Country::IS => "is-IS",
                Country::IE => "en-IE",
                Country::IT => "it-IT",
                Country::JE => "en-GB",
                Country::KV => "en-GB",
                Country::LV => "lv-LV",
                Country::LI => "de-LI",
                Country::LT => "lt-LT",
                Country::LU => "fr-LU",
                Country::MT => "mt-MT",
                Country::MD => "en-GB",
                Country::MC => "fr-MC",
                Country::ME => "en-GB",
                Country::NL => "nl-NL",
                Country::MK => "en-GB",
                Country::NO => "nb-NO",
                Country::PL => "en-US",
                Country::PT => "pt-PT",
                Country::RO => "ro-RO",
                Country::RU => "ru-RU",
                Country::SM => "en-GB",
                Country::RS => "sr-Latn-BA",
                Country::SK => "sk-SK",
                Country::SI => "sl-SI",
                Country::ES => "es-ES",
                Country::IC => "es-ES",
                Country::SE => "sv-SE",
                Country::CH => "de-CH",
                Country::TR => "tr-TR",
                Country::UA => "uk-UA",
                Country::GB => "en-GB",
                Country::VA => "en-GB",
                Country::CA => "en-CA",
                Country::PR => "es-PR",
                Country::US => "en-US",
            }
        }
    }
}
